### ISSUE TITLE
Use of unresolved identifier 'PostgresDatabaseConfiguration'

### ISSUE THREAD

**Issue by nightslide** [PerfectlySoft/Perfect-CRUD#39]
I just tried to implement the example given in Readme.md, and faced such a problem at the very beginning.

`let db = Database(configuration: 
	try PostgresDatabaseConfiguration(database: postgresTestDBName, host: "localhost"))`

- I have PostgreSQL installed on my Mac

- I have PerfectCRUD dependency in my Package.swift

Should I implement 'PostgresDatabaseConfiguration' by myself?

**Comment by kjessup** [comment]
No, you should just need to `import PerfectPostgreSQL`.
You can see it in action in the tests (it's typealiased, but you get the picture):

https://github.com/PerfectlySoft/Perfect-PostgreSQL/blob/master/Tests/PerfectPostgreSQLTests/PerfectPostgreSQLTests.swift#L30

**Comment by nightslide** [comment]
Solved. I tried to add PerfectPostgreSQL dependency like this
`.package(url: "https://github.com/PerfectlySoft/Perfect-PostgreSQL.git", .upToNextMinor(from: "3.0.0"))`
So I received PerfectPostgreSQL 3.0.6 instead of 3.1.1. 
Thanks a lot ^^
