### ISSUE TITLE
Any plans to add a .returningPrimaryKey for Inserts ?

### ISSUE THREAD

**Issue by idi888** [PerfectlySoft/Perfect-CRUD#52]
return the pk on insert

**Comment by burgercode** [comment]
Any news about this ?

**Comment by burgercode** [comment]
@idi888 Hello ! Do you have any news about this ? Or did you found a way to to this ?

**Comment by kjessup** [comment]
We've added the following for MySQL, SQLite and Postgres, though note the Postgres additions differ.
https://github.com/PerfectlySoft/Perfect-CRUD#dbspecific

CRUD 1.2.2
