### ISSUE TITLE
How to handle inserts with auto increment column

### ISSUE THREAD

**Issue by fgrogan** [PerfectlySoft/Perfect-CRUD#58]
I was wondering what would be the proper way to handle inserting a new row for something with an auto incrementing column. If I make the field optional in the data model class I can insert it but don't see a way I can get the insert id. Is there a way to get the id once it is inserted?

**Comment by kjessup** [comment]
We've added the following for MySQL, SQLite and Postgres, though note the Postgres additions differ.
https://github.com/PerfectlySoft/Perfect-CRUD#dbspecific

CRUD 1.2.2
